# Generated by Django 4.1.5 on 2023-01-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='post_default.jpg', null=True, upload_to=''),
        ),
    ]
